DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Bid;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS User;

CREATE TABLE User(
        userID VARCHAR(100) PRIMARY KEY NOT NULL,
        rating INT,
        location VARCHAR(100),
        country VARCHAR(100)
);

CREATE TABLE Item(
	itemID INT PRIMARY KEY NOT NULL,
	name VARCHAR(100) NOT NULL,
	currently DOUBLE(11,2) DEFAULT NULL,
	buy_price DOUBLE(11,2) DEFAULT NULL,
	first_bid DOUBLE(11,2) DEFAULT NULL,
	started DATETIME NOT NULL,
	ends DATETIME NOT NULL,
	userID VARCHAR(100) NOT NULL,
	description TEXT,
	FOREIGN KEY (userID) REFERENCES User(userID)
);

CREATE TABLE Category(
	itemID INT NOT NULL,
	category VARCHAR(100) NOT NULL,
	CONSTRAINT PK_Category PRIMARY KEY (itemID, category),
	FOREIGN KEY (itemID) REFERENCES Item(itemID)
		ON DELETE CASCADE
);

CREATE TABLE Bid(
	itemID INT NOT NULL,
	userID VARCHAR(100) NOT NULL,
	time DATETIME NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_Bid PRIMARY KEY (itemID, userID, time),
	FOREIGN KEY (itemID) REFERENCES Item(itemID)
		 ON DELETE CASCADE,
	FOREIGN KEY (userID) REFERENCES User(userID)
		ON DELETE CASCADE
);
